"""Remove is_approved from doctors table

Revision ID: 4cd1b0f2622c
Revises: 927f653dbb8b
Create Date: 2025-06-07 19:08:46.450156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd1b0f2622c'
down_revision: Union[str, None] = '927f653dbb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'clinic_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('doctors', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.create_unique_constraint(None, 'doctors', ['user_id'])
    op.drop_column('doctors', 'is_approved')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PATIENT', 'DOCTOR', 'STAFF', 'ADMIN', name='userrole'),
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING_VERIFICATION', 'PENDING_ACTIVATION', 'DISABLED', 'ACTIVE', 'DEACTIVATED', 'RED_TAG', name='accountstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending_verification'::character varying"))
    op.drop_column('users', 'doctor_specialization')
    op.drop_column('users', 'doctor_bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doctor_bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('doctor_specialization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'status',
               existing_type=sa.Enum('PENDING_VERIFICATION', 'PENDING_ACTIVATION', 'DISABLED', 'ACTIVE', 'DEACTIVATED', 'RED_TAG', name='accountstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending_verification'::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('PATIENT', 'DOCTOR', 'STAFF', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('doctors', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doctors', type_='unique')
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.alter_column('doctors', 'bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('doctors', 'clinic_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ### 