"""Add password reset fields to user model

Revision ID: 2715ac7b3fd6
Revises: 7d6de07f5793
Create Date: 2025-06-04 00:38:59.925688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2715ac7b3fd6'
down_revision: Union[str, None] = '7d6de07f5793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('reset_token_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('reset_attempts_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reset_locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PATIENT', 'DOCTOR', 'STAFF', 'ADMIN', name='userrole'),
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING_VERIFICATION', 'PENDING_ACTIVATION', 'DISABLED', 'ACTIVE', 'DEACTIVATED', 'RED_TAG', name='accountstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending_verification'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('PENDING_VERIFICATION', 'PENDING_ACTIVATION', 'DISABLED', 'ACTIVE', 'DEACTIVATED', 'RED_TAG', name='accountstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending_verification'::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('PATIENT', 'DOCTOR', 'STAFF', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'reset_locked_until')
    op.drop_column('users', 'reset_attempts_count')
    op.drop_column('users', 'reset_token_created')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token_hash')
    # ### end Alembic commands ###
